### ISSUE TITLE
NodeOS

### ISSUE THREAD

**Issue by piranna** [NodeJsMadrid/talks#1]
[Sistema operativo](https://github.com/NodeOS/NodeOS) (en fase de desarrollo) construido sobre un kernel Linux y usando Node.js como runtime.

Soy Jesús Leganés Combarro "[piranna](https://github.com/piranna)", estoy terminando la carrera de Ingenieria Informatica (plan antiguo, la de 5 años, la de masocas :-P ) y trabajo a jornada completa en un [proyecto de investigacion sobre transmision de multimedia](http://kurento.org/) en la [Universidad Rey Juan Carlos](http://www.urjc.es/), y llevo trasteando y haciendo inventos locos con los ordenadores (y [ganando premios con ellos](http://shareit.es/)) desde hace varios años :-)

La charla no la podre dar a corto plazo por falta de tiempo, pero tengo intencion de hacerla mas adelante si hay interes :-) Se puede aprovechar este issue para plantear dudas y comentar que aspectos se quiere que hable durante la charla :-)

**Comment by alexfernandez** [comment]
Tenemos un hueco este 24 de enero, ¿te animas? Pásame título, descripción y una breve bio por correo, please.

**Comment by piranna** [comment]
¿Sabado? Joder que fecha mas rara... :-P Bueno, ahora que he terminado
los examenes puedo encontrar un hueco :-) ¿De cuanta duracion seria la
charla y en que nivel debo darla? ¿Introductorio para explicar solo
que es? ¿Para sysadmins? ¿Para desarrolladores? ¿Para hackers? ¿Para
reclutar a gente? ¿Un poco de todo...? :-P

El titulo, descripcion y bio seria mas o menos lo que esta puesto en
el primer mensaje, pero un poco mas limpio podria ser algo asi:
 desarrollando un servidor multimedia
Titulo: NodeOS

Descripcion: Sistema operativo ligero construido sobre Linux y Node.js

Bio: Soy Jesús Leganés Combarro "piranna", estoy terminando la carrera
de Ingenieria Informatica (plan antiguo, la de 5 años, la de masocas
:-P ) y trabajo a jornada completa desarrollando APIs para Node.js y
Javascript en un proyecto de investigacion de la Universidad Rey Juan
Carlos desarrollando un servidor multimedia aunque siempre he sido mas
de desarrollo de sistemas :-P Llevo trasteando y haciendo inventos
locos con los ordenadores (y ganando premios con ellos) desde hace
varios años, y ahora estoy cumpliendo mi sueño desde que era un crio
de hacer mi propio sistema operativo... y a la gente le esta gente le
esta gustando :-D

2015-01-11 11:44 GMT+01:00 Alex Fernández <notifications@github.com>:
> Tenemos un hueco este 24 de enero, ¿te animas? Pásame título, descripción y
> una breve bio por correo, please.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by alexfernandez** [comment]
Dios, cada día estoy más tonto: es el martes día 27 de enero, a las 19:30, de una media hora. Nivel avanzado (ya tenemos charla introductoria a las 19:00), sin miedo a meterte en profundidades. ¿Te apunto pues?

**Comment by piranna** [comment]
Ok, apuntame. Salgo de trabajar de Fuenlabrada a las 18:00, pero podria
hacer algun apaño. ¿Por donde seria? Iria en transporte publico...

El 11 de enero de 2015, 13:16, Alex Fernández <notifications@github.com>
escribió:

> Dios, cada día estoy más tonto: es el martes día 27 de enero, a las 19:30,
> de una media hora. Nivel avanzado (ya tenemos charla introductoria a las
> 19:00), sin miedo a meterte en profundidades. ¿Te apunto pues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeJsMadrid/talks/issues/1#issuecomment-69492480>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by alexfernandez** [comment]
Vale, si puedes intentar salir antes, mejor :)  Va a ser en kunlabori, cerca de Avenida América: http://kunlabori.es/contacto/

**Comment by piranna** [comment]
Ok, perfecto entonces :-)

2015-01-11 13:21 GMT+01:00 Alex Fernández <notifications@github.com>:

> Vale, si puedes intentar salir antes, mejor :) Va a ser en kunlabori,
> cerca de Avenida América: http://kunlabori.es/contacto/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeJsMadrid/talks/issues/1#issuecomment-69492651>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by alexfernandez** [comment]
Gracias por la charla. Preguntan en el [Meetup](http://www.meetup.com/Node-js-Madrid/members/47823222/) si conseguimos grabarla, se perdió la imagen o algo, ¿no?

**Comment by piranna** [comment]
Se grabo la charla, pero tuvimos un fallo con el Hangout y solo se grabo el
audio :-(

2015-02-03 22:48 GMT+01:00 Alex Fernández <notifications@github.com>:

> Gracias por la charla. Preguntan en el Meetup
> <http://www.meetup.com/Node-js-Madrid/members/47823222/> si conseguimos
> grabarla, se perdió la imagen o algo, ¿no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeJsMadrid/talks/issues/1#issuecomment-72742198>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by alexfernandez** [comment]
Charla dada con gran éxito de crítica y público, cierro.

**Comment by piranna** [comment]
:+1:
