### ISSUE TITLE
Socialmente conectado. Cómo autenticarte con passport en nodejs

### ISSUE THREAD

**Issue by therealpablors** [NodeJsMadrid/talks#10]
# Título (opciones)
Login a lo passport en node | Socialmente conectado | Cómo autenticarte con passport en nodejs

# Descripción
Cuando creamos una aplicación web una de las primeras cosas contra las que nos enfrentamos es al sistema de login. 
La idea es compartir mi experiencia usando passport y hacer un sencillo ejemplo sobre el uso de las estrategias en passport para hacer distintos tipos de login: twitter, local.

# Bio
Software engineer. Canario afincado en Madrid con ganas de aprender y usar la creatividad creando software. Mi pasión y curiosidad por el mundo startup me llevó a formar parte del equipo ganador del [III startup weekend de tenerife] (https://medium.com/@therealpablors/como-salir-ganador-de-un-startup-weekend-aunque-nadie-vote-t%C3%BA-idea-52e7a26f9a61?source=most-recommended) y a trabajar en startups como 6cero.com o crear productos como influencers.movistar.es, footballerid.com. Me encanta la docencia y tengo ganas de quitarme el miedo de compartir en la comunidad mis experiencias con javascript ;)

@therealpablors
http://therealpablors.com
http://medium.com/@therealpablors

**Comment by alexfernandez** [comment]
Buenas, ¿esta charla la ves como de iniciación o avanzada? Y, ¿te ves con ganas de darla este mismo mes?

**Comment by therealpablors** [comment]
Siempre y cuando pueda tener una semana para preparar el material no tendría problema de darla este mes e incluso repetirla en jsDay ;)
En cuanto al nivel, básicamente mi idea era mostrar el login con alguna red social, o varias dependiendo de las opciones, y el login local tirarlo contra un objeto plano (sin base de datos). Yo diría que es intermedio :P

**Comment by piranna** [comment]
¿A que te refieres con lo de login local?

**Comment by alexfernandez** [comment]
Buenas, Aurelia,

¿Tendrías disponibilidad para el martes 16 de junio? Queremos organizar un Meetup en colaboración con el [Open Expo Day](http://www.openexpo.es/).

¡Gracias!

**Comment by therealpablors** [comment]
Hola chicos. No sé por qué no he visto estos mensajes mediante alguna notificación de hithub. Respondo a piranna:

Me refiero a login local como la forma de procesar un registro/login con una cuenta de usuario y un password mediante passport. Para ello se utiliza passport-local y creo que es interesante tocar ese tema.

Ahora a Alex ;) Me parece perfecto el 16 de junto :D
