### ISSUE TITLE
Charla sobre Medbravo

### ISSUE THREAD

**Issue by Auridev** [NodeJsMadrid/talks#11]
Hola Alex, 

Ahí va nuestra propuesta de charla.

Presentación de Medbravo: red online de ensayos clínicos en cáncer 
www.medbravo.org

Podéis ver quienes somos en estos videos: 
www.youtube.com/watch?v=1xk5gdCGaBA
www.youtube.com/watch?v=n_Sra9PQnJc

Saludos,
Aurelia

**Comment by alexfernandez** [comment]
¡Muchas gracias por la propuesta! Un par de cosas:

* ¿Puedes editarla y añadir una breve descripción y bio de la ponente?
* ¿La ves como charla de iniciación o avanzada?

Seguramente la programemos para el mes que viene, si te viene bien; para este mes estamos planificando una nueva edición de NodeSchool Madrid.

**Comment by alexfernandez** [comment]
Buenas, Aurelia,

¿Tendrías disponibilidad para el martes 16 de junio? Queremos organizar un Meetup en colaboración con el [Open Expo Day](http://www.openexpo.es/).

¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, esta propuesta lleva mucho tiempo abierta, la cierro. Reabrid si queréis volver a lanzarla, ¡gracias!
