### ISSUE TITLE
Serve-Me

### ISSUE THREAD

**Issue by muit** [NodeJsMadrid/talks#12]
# Serve-me
Serve-me es un modulo para la creación de applicaciones web simples con node.
[NPM](https://www.npmjs.com/package/serve-me) - [GitHub](https://github.com/muit/serveme)

## Descripción
Buenas. Hace unos meses me encontré con la ausencia de módulos de servidores paginas estáticas, o casi estáticas. Si, está express por ejemplo, pero incluyen mas de lo que uno suele necesitar, y eso los hace lentos.

Así que hice uno, y lo optimicé (sin profiling :( ) para que fuera rápido.

Serve-me soporta rutas, sesiones, multithreading y esta basado en eventos.

## Bio
Programador de backend y videojuegos. Lead & AI programmer en Demigod Studios.
Programo por gusto, y por aprender algo nuevo cada día. Cacharreo todo lo que puedo y de vez en cuando salen cosas interesantes como  serve-me. Por supuesto, un novato dispuesto a aprender.

@muitxer - miguel_3c@hotmail.com

**Comment by muit** [comment]
Actualmente estoy con otro proyectillo que seria como una plataforma social con redis y websockets. Dudo que sea de mucho interes pero por si acaso lo dejo aqui.
https://github.com/muit/SocialServer

**Comment by alexfernandez** [comment]
En principio esta charla ya no nos entra esta temporada, salvo cancelaciones de última hora. La segunda yo la movería a un segundo issue, me parece perfecta para iniciación. Las dejamos ambas para septiembre, ¿vale?

**Comment by muit** [comment]
Ok. A mi si me avisais con tiempo lo que sea :)

**Comment by alexfernandez** [comment]
Llegó el momento de planificar las charlas de septiembre. ¿Estarías disponible para el martes día 22?

**Comment by muit** [comment]
Si, por la tarde

**Comment by alexfernandez** [comment]
Buenas, ¿esta propuesta sigue en pie? Lo digo por cerrarla si no...
