### ISSUE TITLE
Cómo montar un proyecto con Node y Express.js

### ISSUE THREAD

**Issue by luisddm** [NodeJsMadrid/talks#13]
Nuestra propuesta consiste en "diseccionar" un proyecto hecho en Express.js.

## El proyecto

Por un lado, se ofrece un punto de entrada a una API que recibe información periódica de dos routers. Ambos routers están monitorizando todos los dispositivos que se encuentran en su radio de alcance mediante un tcpdump interno. Básicamente vuelcan esta info sobre la API de forma periódica, transformando la salida de tcpdump en un array JSON. Esta info contiene principalmente la dirección MAC y la potencia de la señal de cada dispositivo.

La información que entra a la API se va almacenando en una base de datos MongoDB, pero no en bruto, sino que únicamente hay una entrada por cada dispositivo con la información más reciente de cada uno. Además, habrá un proceso que limpiará los dispositivos de la base de datos que no se hayan "visto" desde hace demasiado tiempo.

Hay también una parte frontal que de forma periódica hace una consulta a otro punto de entrada de la API, esta vez de lectura, y obtiene los datos de cada dispositivo para dibujarlos como pertenecientes a un router, a otro, o incluso a ambos si se encuentran cerca uno del otro y el dispositivo a medio camino. En esta parte frontal se pueden ver tablas o gráficos con distintas estadísticas y visualizaciones.

## Nuestra propuesta

Con este proyecto se puede hacer hincapié en muchas cosas: desde el manejo básico de bases de datos MongoDB, hasta algunas técnicas de polling para obtener info del back y actualizar los elementos del front en consecuencia sin intervención del usuario. El proyecto podría servir como base para presentar estos elementos.

Pero si tenemos que hacer una propuesta más concreta, podríamos centrarnos en hacer una introducción sobre generación y consumo de APIs REST en Node y Express.js.

**Comment by alexfernandez** [comment]
Me parece muy interesante. De hecho creo que hay dos charlas posibles: una de iniciación y otra avanzada. ¿Es así?

**Comment by luisddm** [comment]
Efectivamente, se podrían tratar asuntos muy básicos como instalar Express.js y hacer una API muy sencilla para ser consumida por un servicio de front, explicando también lo

**Comment by luisddm** [comment]
Efectivamente, se podría hacer una charla de iniciación contando cómo se instala Express.js y cómo se genera una API sencillita para ser consumida por un servicio front de forma rápida, intercambiando algunos datos en JSON.

O se puede complicar explicando cómo se hace una API compleja que tenga que adaptarse más a rajatabla a los paradigmas de REST, incluyendo aquí un poco de teoría sobre cómo y cuándo se deben usar los verbos POST, PUT, GET, las cabeceras HTTP, etc., y presentando también la relación con la capa de persistencia, así como la interacción en el front usando JQuery o AngularJS.

Estamos abiertos a cualquiera de las dos posibilidades en función del interés que pueda tener una cosa u otra. Respecto al enfoque, yo personalmente, que trabajo ahora en front, puedo aportar más acerca de la interacción entre la API, el navegador y las librerías de front, y no tanto acerca de la base de datos, pero todo es cuestión de estudiarlo :)

**Comment by alexfernandez** [comment]
Entendido. La charla queda ya para el próximo curso; te avisaré con un mes de antelación para prepararte, ¿vale?

**Comment by luisddm** [comment]
Perfecto!

**Comment by alexfernandez** [comment]
Tenemos un hueco para el día 22, aunque sea una locura igual te interesa darla. ¿Me dices algo cuanto antes, para pasar al siguiente de la lista si no puedes? ¡Gracias!

**Comment by luisddm** [comment]
Ufffff muchas gracias, pero me va a ser completamente imposible prepararla con tan pocos días, y además no podré estar disponible ese día... Sin embargo podemos hablarlo para el mes que viene o un poco más adelante si os parece, y así puedo además elaborar una propuesta más concreta que ya pondré por aquí a ver si resulta interesante.

**Comment by alexfernandez** [comment]
No hay problema, lo comprendo. ¡Gracias por responder tan rápido!

**Comment by alexfernandez** [comment]
¿Esta propuesta sigue en pie? Lo digo por cerrarla, y reabrirla cuando queráis volver a presentarla.

**Comment by luisddm** [comment]
Ciérrala por ahora porque desgraciadamente la cosa está muy liada :( Me gustaría retomar la idea próximamente, avisaré cuando sea posible!
