### ISSUE TITLE
Node JS & second screen

### ISSUE THREAD

**Issue by iav2014** [NodeJsMadrid/talks#14]
Node JS en plataformas second screen (rest & socket.io).
Diseño, arquitectura / escalabilidad y securización en los datacenters.
Caso práctico en  masterchef españa (junior/senior).
El reto: diseño de una plataforma escalable multiprograma
Las cifras: entre 8 y 16 millones de accesos de accesos por programa.
Los limites presupuestarios: el coste del datacenter.
La tecnologia: mix de  node js, mongodb, redis, mysql, php, haproxy, F5, nginx-plus,,,,,¿jxcore?
La seguridad: metodos de accesos, cifrados simetricos, fail2band, ssh,,,
- bio -
Programador por vocación. He tenido la suerte de poder hacer de mi hobbie una profesión. Apasionado de la inteligencia artificial y de la algoritmia en general. Comencé realizando virus y programas residentes en assembler 86 y 80x86 así como drivers de comunicaciones y tarjetas gráficas en c, lenguajes que tengo muy presente en mi forma de estructurar el código. Mi carrera profesional ha estado de alguna forma unida a  TI+D donde conocí mucha gente tech en los diferentes proyectos que pude abarcar durante 14 años que colaboré con ellos. Recientemente reciclado en Node JS & vert.x (2011) aprendiendo el paradigma de programación asincrona, intentando buscar soluciones de escalabilidad y rendimiento en plataformas second screen,,,,

**Comment by alexfernandez** [comment]
Buenas, Nacho,

Muy interesante la charla, entiendo que es avanzada. ¿Puedes añadir una bio tuya, y una descripción un poco más extensa para tenerla cuando la programemos?

Te avisaremos con un mes de antelación cuando te vaya a tocar.

**Comment by alexfernandez** [comment]
Atraco a mano armada: ¿te da tiempo a prepararla para finales de este mismo mes?

**Comment by iav2014** [comment]
Pues te lo confirmo el 15 ya que justo ahora en un rato me hago una resonancia de rodilla,,, :-((

Enviado desde mi iPhone

**Comment by alexfernandez** [comment]
¡Vale, suerte!

**Comment by iav2014** [comment]
Buenas, 
Que fechas manejas, tendria que preparar algo de docu y una demo,
La prox. semana lo veo un poco pronto ya que viajo a barcelona no se aun el dia, pero supongo que para la primera quincena de octubre podria ser,
Dime que dias habias pensado,,,,


Enviado desde mi iPad

**Comment by alexfernandez** [comment]
Estábamos pensando en el 22, justo dentro de una semana. De hecho te estaba esperando para anunciar la charla. Confírmame si te viene bien o no, please.

**Comment by iav2014** [comment]
Hola,
no me da tiempo para el 22, demasiado pronto,
hasta este viernes no me dicen que día tengo que ir por trabajo a BCN y
podría coincidirme
dime que otras fechas podrían ser,


2015-09-15 21:01 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
No hay problema, la dejamos para el mes que viene o el siguiente. Era demasiado precipitado, pero gracias :)

**Comment by iav2014** [comment]
me sabe mal no tenerlo para el 22, queria hacer una demo conectando 10k
sockets para la parte que hablo de eso, y enviar un mensaje a esos 10k
users, de hecho la estoy preparando paralelamente al trabajo,
pero hoy me han dado la noticia de que tengo que terminar unos servicios
para un programa que se llama La Bascula, que empezamos el domingo pasado,
y tengo que tenerlos para el viernes ya que suben las apps justo ese dia
(se conectaron 300.000 el domingo),,,
Imagino que se te habra quedado ese hueco libre ese dia no?




2015-09-16 10:01 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Hey, ¿el programa "La Báscula" de Canal Sur? Es de los realities más infumables que he visto nunca, ¡mola! :)

No te preocupes, rellenaremos el hueco como sea. Son los problemas del directo.

**Comment by iav2014** [comment]
Si justo, es el programa de la Bascula, llevamos el second screen desde
aqui.
Aunque te parezca mentira lo ve mucha gente (yo no lo he visto, solo
monitorizo los servidores el domingo,,,). Solo nos ha dado tiempo a
publicar la app de android, y lo han visto 300.000 personas en dos dias,,,
eso si los node servers no han llegado ni al 5% jeje,


El 16 de septiembre de 2015, 10:23, Alex Fernández <notifications@github.com

**Comment by alexfernandez** [comment]
Pues suena muy interesante, ¡volveremos a hablar! :)

**Comment by alexfernandez** [comment]
Buenas, entiendo que esta charla fue la que se dio en las oficinas de Everis. ¿Sigue en pie para darla también en Node.js Madrid, para los que nos la perdimos?

**Comment by iav2014** [comment]
Hola Alex, cuanto tiempo,
efectivamente esa fue la que se hizo en everis el pasado noviembre.
En principio sigue en pie, solo que ha habido algunos cambios a nivel
empresariales desde entonces y tengo que ver cómo tengo que gestionarlo
ahora.
En estos momentos, como sabes, estamos en emisión, y lo ideal seria
agendarlo para más adelante (creo que acaba a primeros de Julio).


2016-05-10 12:26 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Vale, entonces la dejamos ya para el curso que viene. ¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, @iav2014, ¿para finales de septiembre estás disponible? Sería lunes 26 o martes 27.

**Comment by iav2014** [comment]
perdona Alex por tardar en responder,
hasta qué dia hay  margen para confirmartelo?
por temas laborales tengo pendiente desplazamientos y a dia de hoy no se si
me coinciden.
La prox. semana podria decirte,
ya me dices,


2016-09-08 22:20 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Cuanto antes lo sepas mejor, te esperamos.

**Comment by iav2014** [comment]
en principio cuenta conmigo para el 26 de sep.
si hubiera algún problema debido al trabajo te aviso con tiempo para que
puedas dar cabida a otro ponente.
Pásame las coordenadas del sitio / hora / conectividades etc.
Dime si necesitas un brieffing de proyecto, ya que la plataforma que he
diseñado tiene parte rest, parte servicios, parte socket e2e,,etc. Lo mismo
interesa mas explicar el escalamiento socket y los servicios tipo
pokemon-go que se han hecho para realidad aumentada basado en un modelo
subscriber,,,,
Me encnta enseñar codigo con objeto de mejorarlo y discutirlo, pero no se
si las clausulas de confidencialidad de mi empresa me permitiran hacerlo,
si te parece llamame y lo hablamos,





2016-09-11 17:38 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Vamos a planificar la charla, y luego habrá tiempo de cambiarla.

**Comment by alexfernandez** [comment]
Charla hecha en septiembre.
