### ISSUE TITLE
Buscar, almacenar y analizar datos geolocalizados con NodeJS

### ISSUE THREAD

**Issue by hhkaos** [NodeJsMadrid/talks#15]
## Descripción

Usando la [API REST de ArcGIS Online](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/The_ArcGIS_REST_API/02r300000054000000/) se pueden realizar multitud de cosas:
* [Almacenar información geolocalizada](https://developers.arcgis.com/en/features/cloud-storage/)
* Generar datos derivados a partir de otros
* [Realizar análisis espacial](https://developers.arcgis.com/rest/analysis/): agregar datos, agrupar por cercanía, buscar lugares "gemelos", etc.
* [Enriquecer capas de datos](https://developers.arcgis.com/en/features/geo-enrichment/)
* Etc.

En la charla veremos cómo funciona la API de ArcGIS y el módulo [arc-node](https://www.npmjs.com/package/arc-node), un proyecto que en su primera versión se ha creado para facilitar el trabajo a la hora de trabajar con la API REST de ArcGIS.

## Bio de ponente

Informático de profesión y emprendedor de vocación. Desde 2009 desarrollando webs y emprendiendo proyectos desde 2007. He trabajado en varias startups, visitado y trabajado fugazmente en Silicon Valley, etc. Actualmente soy organizador de las comunidades de [Iniciador Madrid](http://iniciador.com/madrid) (emprendedores) & [Geo Developers](geodevelopers.org/members). Además trabajo en [Esri España](http://www.esri.es) como responsable de los programas de desarrolladores y emprendedores.

+info: [rauljimenez.info](http://www.rauljimenez.info) & [linkedin](es.linkedin.com/in/jimenezortegaraul)

**Comment by alexfernandez** [comment]
¡De nuevo muy completa! En Node.js tenemos menos backlog, seguramente te tocará en breve.

**Comment by hhkaos** [comment]
jejej, sin problema :), ya me decís entonces

**Comment by alexfernandez** [comment]
Tenemos un hueco para el día 22 de este mes (dentro de 6 días), aunque sea una locura igual te interesa darla. ¿Me dices algo cuanto antes, para pasar al siguiente de la lista si no puedes? ¡Gracias!

**Comment by hhkaos** [comment]
Buenas Alex, sí que es un poco precipitado, lo dejamos para otro mes, vale?
(que tengo q preparar algunas cosillas y no me da tiempo).

Gracias a ti

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/perfil-profesional>
*GeoRemindMe <http://www.georemind.com>, a whole world of recommendations
to be discovered.*
GeoRemindMe!

*Contact*
Urgent contact: P*lease call me at +34 652 38 43 50 *
Chat/IM *:* *hhkaos at google (gtalk)* | *kaos_cs (skype)*
Social networks:  <http://www.linkedin.com/pub/dir/raul/jimenez%20ortega>
<http://www.facebook.com/hhkaos>  <http://www.twitter.com/raul_en>
<http://www.xing.com/profile/Raul_JimenezOrtega>

2015-09-16 22:53 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Me imagino. ¡Gracias por responder tan rápido! Te aviso la próxima vez con más tiempo :)

**Comment by alexfernandez** [comment]
Buenas, ¿estás disponible para este martes 24?

**Comment by alexfernandez** [comment]
Cerrando issue, please reabre cuando puedas preparar la charla. ¡Gracias!

**Comment by hhkaos** [comment]
Ostras crack, perdona que no había visto el mensaje. Hasta Junio estoy un poco liado porque tengo que prepararme varias charlas para el 31 que organizo un [evento en Esri](http://desarrolladores.esri.es/devsummit)

Lo dejamos para mediados/finales de Junio?

**Comment by alexfernandez** [comment]
Vale, en principio la apuntamos para junio. ¡Gracias!

**Comment by hhkaos** [comment]
Ok, qué fecha tentativa manejamos? :)

**Comment by alexfernandez** [comment]
Normalmente nos reunimos la última semana de junio, así que sería el 23 o el 30 de junio, ¿alguna preferencia?

**Comment by hhkaos** [comment]
Miércoles 29 sería buen día que el 23 tengo otro evento y el finde me voy a
Portugal, así tengo un par de días para repasar y cerrar los últimos
detalles :).

Si va bien avísame cuándo tengamos la sala que le doy difusión al evento en
la comunidad de geodevelopers <http://www.meetup.com/Geo-Developers/> tb :)

Un abrazo!

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/>
*Urgent contact:* *+34 652 38 43 50 *

* <http://rauljimenez.info/> **
<https://es.linkedin.com/in/jimenezortegaraul> **
<https://github.com/hhkaos>
<https://plus.google.com/+RaulJimenezOrtega/posts> [image:
http://rauljimenez.info/skype.html] <http://rauljimenez.info/skype.html>
<http://www.twitter.com/hhkaos>  <https://www.youtube.com/user/HHKaoS> **
<http://diigo.com/user/hhkaos/> **
<http://stackoverflow.com/users/3541972/hhkaos>*

**Comment by alexfernandez** [comment]
Vale, @hhkaos, vamos a ir buscando sala para el 29.

**Comment by alexfernandez** [comment]
Hecha en junio 2016.
