### ISSUE TITLE
Envoltorio de herramientas nodejs para integración continua, testing y más... con piscosour

### ISSUE THREAD

**Issue by sbonacho** [NodeJsMadrid/talks#16]
**Descripción**

En el equipo de Tooling del proyecto Cellsjs hemos desarrollado una herramienta que envuelve la ejecución de cualquier herramienta nodejs que intervenga en el proceso de construcción y prueba de una aplicación híbrida basada en polymer. Estos son los puntos de la charla.

- Breve presentación de las herramientas que usamos para crear, construir, empaquetar y probar nuestras aplicaciones híbridas. gulp, yeoman, cordova, polyserv, lint, eslint,  cucumber, mocha, vulcanized, jshint, etc... 
- ¿Por qué un proceso automatizado de integración continua? (Breve)
- ¿Qué es piscosour?  Mediante un ejemplo práctico hecho en el momento, veremos los siguientes conceptos de piscosour.
    - Piscosour envuelve todas las herramientas de desarrollo por línea de comando (CLI), creando workflows comprobables ejecutados también por línea de comando.
    - Piscosour no remplaza otras herramientas, coexiste con todas permitiendo el mejor aprovechamiento y simbiosis de todas ellas.
    - Los shots son componentes sencillos y reutilizables mediante una simple dependencia npm. 
    - Cada ejecución de Piscosour genera un fichero junit.xml que posibilita la mejor integración con los orquestadores más populares de C.I. como Jenkins, Hudson, Bamboo, etc.
    - Piscosour mantiene todos los sets de herramientas ordenados bajo la misma receta, así podrías tener recetas para polymer, angularjs, react, instalaciones, utilidades de sistema... y usarlos en cualquier workflow que necesites.

https://github.com/cellsjs/piscosour

**Bio**

Soy físico pero me dedico a esto de la informática desde hace 17 años, emprendedor en varias ocasiones (Intelygenz y solsop) pero ahora trabajo por cuenta ajena en uno de los proyectos más innovadores de BBVA: Cellsjs. He tocado prácticamente de todo, empezando por la configuración de hardware, redes, sistemas operativos, software base, desarrollos basados en Java, JEE y cosas de esas antiguas. En los últimos años más centrado en QA, devops y en Integración continua, en el último año centrado en polymer y en los últimos meses en nodejs. No soy un experto en nodejs, pero sí perro viejo muy acostumbrado a aprender.

**Comment by alexfernandez** [comment]
Suena muy interesante. ¿Es una charla avanzada, supongo?

**Comment by sbonacho** [comment]
No demasiado, si es cierto que hace falta haber trabajado con algunas de
las herramientas que menciono , pero tampoco es necesario un conocimiento
muy avanzado de nodejs. Desde luego no es una charla de iniciación,
requiere algo de experiencia por parte de los asistentes..

**Comment by alexfernandez** [comment]
Buenas, ¿estás disponible para el martes 24?

**Comment by sbonacho** [comment]
Buenas!! no hay problema!

Tengo un taller preparado ,  bastante intenso, que lleva unas 4-5 horas más
o menos. Esto sería simplemente una presentación, no? Cuanto tiempo sería?


2016-05-10 12:04 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Nuestro formato habitual es hacer dos charlas de media hora, pero si no hay más charlas podemos hacer un taller si quieres un sábado, de 4 horas.

¿Estarías dispuesto a dar una charla de media hora si se da la ocasión? Si es así, vamos a esperar a ver si hay alguien más interesado, antes de decidirnos, ¿te parece?

**Comment by sbonacho** [comment]
Sin problemas, para el 24 no tengo ningún problema en dar la charla de
media hora, quedo a la espera para cuando decidáis ...

**Comment by alexfernandez** [comment]
¡Publicado en [Meetup](http://www.meetup.com/es-ES/Node-js-Madrid/events/231216390/)! Please, comprueba que esté todo correcto.

**Comment by sbonacho** [comment]
Genial!! Muchas gracias!!

...que emoción... ;)

2016-05-18 15:51 GMT+02:00 Alex Fernández <notifications@github.com>:
