### ISSUE TITLE
Node.js EE o Java as a library.

### ISSUE THREAD

**Issue by cesarvr** [NodeJsMadrid/talks#18]
## Descripción

Quiero presentaros un proyecto en el que trabajo en mi tiempo libre, trata de un node.js add-on escrito C++11 que te permite ejecutar java-code dentro de node.js y así poder acceder a un gran ecosistema de librerías disponibles como API para PDF: (pdfbox, itext) Motores de búsqueda: solr. 

- por que node.js ?
  - extensibilidad con C++
  - libUV
  - chakracore 
  - Debilidades 
- Ella add-on 
  - como funciona ?
  - demo 

## Bio

Actualmente trabajo para Red Hat mobile desarrollando aplicaciones móviles usando node.js en el lado backend, en mi tiempo libre me gusta desarrollar motores gráficos, y últimamente muy interesado en las interioridades de node.js/chakracore.  

Si existe solapamiento entre esta comunidad y *madridjs*, cerrad esta issue.
Gracias

**Comment by alexfernandez** [comment]
¡Buenas, @cesarvr! Interesante. ¿Crees que es más apropiado presentarlo aquí, o en MadridJS? Yo lo veo más apropiado aquí, la verdad.

Parece una charla avanzada, ¿verdad?

**Comment by cesarvr** [comment]
Hola, si yo creo que a este grupo en particular le parecera mas interesante, sobre si la charla es avanzada si quieres puedo empezar en muy alto nivel y hablar un poco sobre como funciona por dentro sin entrar mucho en detalles escabrosos, mi prioridad es que vean las posibilidades que ofrece el plugin para integrar Node y Java, y a modo de bonus puedan ver lo extensible que Node puede llegar a ser.

**Comment by alexfernandez** [comment]
Buenas, @cesarvr, ¿estás disponible para el miércoles 29 de junio?

**Comment by cesarvr** [comment]
Hola @alexfernandez, en principio estare disponible para ese dia, si puede ser a las 19 mejor. saludos.

**Comment by alexfernandez** [comment]
Hecha en junio.
