### ISSUE TITLE
Microservicios: ¿algo nuevo o lo mismo con otro nombre?

### ISSUE THREAD

**Issue by todojs** [NodeJsMadrid/talks#19]
**Título de la charla**: Microservicios: ¿algo nuevo o lo mismo con otro nombre?

**Descripción**: Las grandes organizaciones están "descubriendo" los microservicios como la gran alternativa a los grandes modelos de desarrollo de aplicaciones monolíticas. La literatura sobre estos microservicios está empezando a abundar, pero, ¿realmente son algo nuevo? ¿no es lo mismo con otro nombre? ¿No será que nos quieren vender algo? Probablemente todas las respuestas deban "ser sí y no". En esta charla se podrá discutir en un formato abierto sobre el tema (no es una _master class_ al uso) y descubrir algo más sobre lo que los microservicios pueden hacer por nosotros.

**Bio de ponente**: Pablo Almunia, licenciado en Filosofía, doctor en Informática y master en Administración de Empresas, por lo que termina abarcando desde la metafísica a las finanzas, pasando por algunos temas técnicos que le apasionan como NodeJS, Javascript, MongoDB, etc.

**Comment by alexfernandez** [comment]
Buenas, @todojs, en principio ya tenemos charlas para junio así que ésta quedaría para septiembre.

**Comment by alexfernandez** [comment]
Buenas, @todojs, ¡os toca! Estamos barajando el martes 25, ¿qué tal te viene? Otra cosa, ¿crees que con media hora sería suficiente, o podemos hacer un formato abierto y prolongarlo hasta la hora?

**Comment by alexfernandez** [comment]
La ponemos para el 3 de noviembre, ¿lo planteamos como charla / debate?

**Comment by gelito** [comment]
Debate!!

¿Tenemos gente haciendo cosas en NodeJS que defienda Microservicios? ¿O que defienda monolítico?

En nuestro caso, estamos en medio. Algunos proyectos son monolíticos, pero poco a poco estamos pasando a Microservicios ;-)

**Comment by alexfernandez** [comment]
Realizado en noviembre.
