### ISSUE TITLE
Life after sessions, using tokens for authentication

### ISSUE THREAD

**Issue by xocasdashdash** [NodeJsMadrid/talks#20]
**Título**: Life after sessions, using tokens for authentication

**Descripción**:  Hoy en día ya es bastante común no tener una única app monolítica, esto puede ir desde tener un backend que sirve peticiones para una SPA que internamente realiza peticiones a otra api de usuarios escrita PHP y se integra con el CRM de la casa. Al pasar a un sistema distribuido ya no es tan sencillo (ni barato!) comprobar si un usuario es quien dice ser ni escalar esta solución a cientos de máquinas. En esta charla veremos como implementando un sistema de autenticación con JSON Web Tokens nos puede ayudar a solucionar este problema.

**Bio del Ponente**:  Joaquín Fernández Campo es Ingeniero Técnico de Teleco por la Universidad de Alcalá pero nunca ha ejercido como tal. Actualmente trabaja en Digilant como "Software Engineer" desarrollando en Symfony (PHP) pero en su tiempo libre trastea con Javascript.

**Comment by alexfernandez** [comment]
Buenas, @xocasdashdash, en principio ya tenemos charlas para junio así que ésta quedaría para septiembre.

**Comment by xocasdashdash** [comment]
@alexfernandez Perfecto. Supongo que será sobre la última semana no?

**Comment by alexfernandez** [comment]
Sí, aunque hay que cerrar todavía en qué mes entra, vamos por orden de llegada.

**Comment by xocasdashdash** [comment]
@alexfernandez buenas! Hay alguna fecha tentativa?

**Comment by alexfernandez** [comment]
@xocasdashdash Perdona por no contestarte antes, no vi el mensaje. Había un par de charlas delante de la tuya, este mes / noviembre vamos a hacer la de Pablo Almunia. La tuya quedaría para diciembre o enero, si te viene bien.

**Comment by xocasdashdash** [comment]
@alexfernandez perfecto!

**Comment by alexfernandez** [comment]
Buenas, ¿te viene bien el miércoles 14?

**Comment by xocasdashdash** [comment]
En principio si!

**Comment by alexfernandez** [comment]
Lo pasamos al día 13, publicado: https://www.meetup.com/es-ES/Node-js-Madrid/events/236076273/

**Comment by alexfernandez** [comment]
Hecho: https://www.meetup.com/es-ES/Node-js-Madrid/events/236076273/ ¡Gracias por la charla!
