### ISSUE TITLE
[Introductoria] Curvando el espacio/tiempo con Node.js

### ISSUE THREAD

**Issue by jamg44** [NodeJsMadrid/talks#21]
Charla introductoria 

Curvando el espacio/tiempo con Node.js

Descripción: 
De los productores de _Pásame ese callback_, _La memoria prometida_ y _Vaya par de generadores_, llegan a nuestras manos _Async y Await_.
Haremos un repaso de la evolución de la programación asíncrona en JS, pasando por callbacks, promesas, generadores y demás.
Veremos como aprovecharnos de este nuevo estándar hoy y dejar nuestro código como la patena. También usaremos Typescript en Node.js con sus ventajas e inconvenientes, y alternativas para organizar el código.

Bio de ponente: 
Mi nombre es Javier Miguel (@javiermiguelg) y disfruto cada día de la tecnología haciendo aplicaciones en una pequeña boutique de desarrollo llamada Decode.es
En mi tiempo libre doy clases de Javascript intermedio-avanzado, Node.js, Express, MongoDB y APIs en Keepcoding, disfruto de mis hijos (y esposa!), veo películas y participo en algunos proyectos personales. Intento salir a correr a menudo, pero no lo consigo, quizás un par de veces al año.

**Comment by alexfernandez** [comment]
Buenas, @javiermiguelg, ¿es una charla introductoria o avanzada?

**Comment by jamg44** [comment]
Introductoria

Empezamos con cosas sencillas y las vamos retorciendo poco a poco, en mi
mano está conseguir que no se vuelva complicado!

Javier Miguel

*Linkedin: *http://www.linkedin.com/in/javiermiguel

*Twitter:* @JavierMiguelG <https://twitter.com/JavierMiguelG>

2016-06-16 22:03 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Quedará ya para el curso que viene, porque cerramos el curso ahora en junio. ¡Te avisaremos!

**Comment by jamg44** [comment]
Perfect!

Quizás podemos recomendar ver Inception (Origen) el día anterior para tener
la capacidad abstracción a punto

Abrazo!

Javier Miguel

*Linkedin: *http://www.linkedin.com/in/javiermiguel

*Twitter:* @JavierMiguelG <https://twitter.com/JavierMiguelG>

2016-06-16 23:12 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Buenas, ¿te viene bien el miércoles 14?

**Comment by alexfernandez** [comment]
@jamg44 ¿Te viene bien el próximo miércoles 14?

**Comment by alexfernandez** [comment]
Buenas, @jamg44, esta charla se nos ha quedado pendiente. ¿Sigues queriendo hacerla, por ejemplo a finales de este septiembre?

**Comment by jamg44** [comment]
Cancélala please, además de que salgo de viaje y posiblemente no podría
hasta noviembre, yo creo que ya se ha quedado obsoleta.

Gracias Alex por el interés y perdona por no haberla movido antes.

Un abrazo tio

Javier Miguel

*Linkedin: *http://www.linkedin.com/in/javiermiguel

*Twitter:* @JavierMiguelG <https://twitter.com/JavierMiguelG>

2017-09-14 13:36 GMT+02:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
¡Gracias a ti! Closing.
