### ISSUE TITLE
Bot de resultados electorales en node.js

### ISSUE THREAD

**Issue by jabadia** [NodeJsMadrid/talks#22]
# Title / Título

Bot de resultados electorales en node.js
# Description / Descripción

Para las elecciones del 25-S hicimos un bot al que se le pueden preguntar en twitter los resultados electorales a medida que avanza el escrutinio.

Tiene muchas regex, un poco de machine-learning, algo de ingeniería social... y por supuesto todo hecho en node.js

Contaré cómo está hecho, las distintas aproximaciones previas, los puntos de mejora... 
# Speaker Bio / Bio del Ponente

Javier Abadía: Javier is an experienced technologist that has been working in different technical and management roles over the last 15 years: leading development teams, evangelizing about geographic information technology and even writing software for various models of fighter aircraft. He believes in zero-bug software, paranoid testing, agile methodologies automation and team work.

Passionate runner and skier, he has decided his next big adventure will be to have fun developing the best big-data analytics front-end anyone has ever seen.

Javier has a Computer Engineering Degree from University of Zaragoza (Spain) and a MBA from Instituto de Empresa (IE Business School in Madrid).
# Level / Nivel

Intermedio
# Duration / Duración

30 min

**Comment by gelito** [comment]
+1 

Esta charla tiene muy buena pinta! Hay código accesible??!

**Comment by alexfernandez** [comment]
@jabadia Atraco a mano armada, ¿podrías dar esta charla el próximo martes 13, a las 19h como siempre?

**Comment by jabadia** [comment]
ufff!
vale
donde?

**Comment by alexfernandez** [comment]
Kunlabori, te viene bien?

**Comment by jabadia** [comment]
sip

**Comment by alexfernandez** [comment]
¡Pues allí nos vemos! https://www.meetup.com/es-ES/Node-js-Madrid/events/236076273/

**Comment by alexfernandez** [comment]
Hecho: https://www.meetup.com/es-ES/Node-js-Madrid/events/236076273/ ¡Gracias por la charla!
