### ISSUE TITLE
The CITGM Diaries

### ISSUE THREAD

**Issue by MylesBorins** [NodeJsMadrid/talks#23]
# Title / Título
The CITGM Diaries

# Description / Descripción

The Canary in the Gold Mine is a smoke testing utility that automates running unit tests of various various modules in the Node.js ecosystem, it must pass for all controversial changes and releases. CITGM has been incredibly successful, finding all sorts of regressions across the ecosystem and in node core itself.

I have kept a diary of all the weirdness, lets examine how things break!

# Speaker Bio / Bio del Ponente

Myles Borins is a developer, musician, artist, and inventor

he works for Google as a developer advocate serving the Node.js ecosystem

he graduated with a Master of Music Science and Technology from c.c.r.m.a.

# Level / Nivel

Intermediate
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

30 min

**Comment by alexfernandez** [comment]
Done: https://www.meetup.com/es-ES/Node-js-Madrid/events/238657678/. Thanks for great talk!
