### ISSUE TITLE
El microservicio más grande del mundo

### ISSUE THREAD

**Issue by feliun** [NodeJsMadrid/talks#24]
# Title / Título
El microservicio más grande del mundo

# Description / Descripción
Esta es la historia de cómo un servicio puede crecer manteniendo su status "micro". A nivel técnico trata sobre estrategias para manejar mensajes asíncronos manteniendo la coherencia y el orden.

# Speaker Bio / Bio del Ponente
Felipe Polo es director en GuideSmiths Spain, una consultora nacida en Londres especializada en microservicios y tecnologías full stack. Ferviente defensor de los microservicios como estrategia para aniquilar sistemas legacy. En sus (pocos) ratos libres le gusta hacer deporte y hacer tutoriales de nuevas tecnologías.

# Level / Nivel
Idealmente se requiere un conocimiento intermedio de Node para que la charla sea más enriquecedora para todos.

(Beginner, Intermediate, Advanced)

# Duration / Duración
Unos 45 minutos.

**Comment by alexfernandez** [comment]
Hecho: https://www.meetup.com/es-ES/Node-js-Madrid/events/237845845/ Gracias por la charla!
