### ISSUE TITLE
Scraping at Scale

### ISSUE THREAD

**Issue by furstenheim** [NodeJsMadrid/talks#25]
# Title / Título
Scraping at Scale

# Description / Descripción

Scrapear es una tarea sencilla, pero que se puede volver tediosa si hay que recoger información de muchas webs diferentes. Además, si la información obtenida tiene que mantenerse actualizada, hay que repetir el proceso periódicamente, con la complejidad de que la estructura puede que haya cambiado y que haya que actualizar los scripts.

Una librería estándar que se suele utilizar es Scrapy para Python, pero tiene dos problemas, por un lado hay que repetir mucho código y por otro no es capaz de ejecutar Javascript de cliente, lo cual puede ser necesario cuando la web es dinámica. Es por eso que en Geoblink usamos habitualmente la extensión de Chrome Webscraper. La ventaja es que en un par de clics es posible construir una araña y al ejecutarse en el navegador puede ejecutar el código cliente si lo hubiera.

El principal problema con esta extensión es que automatizar estos procesos es complicado, porque corren en el navegador. Motivados por el lanzamiento de Chrome Headless hemos adaptado la extensión para correr tanto en el navegador como en Node.js https://www.npmjs.com/package/web-scraper-headless

En la charla explicaremos cómo es la arquitectura de las extensiones de Chrome en general, cómo hemos automatizado los procesos de scrapeo usando Webscraper y los problemas que hemos tenido para adaptar el código de una extensión para funcionar en Node.js. Si te gusta el código isomórfico ésta es tu charla.

# Speaker Bio / Bio del Ponente

Gabriel Fürstenheim es Matemático y desarrollador Senior en Geoblink. Es raro verle separado de su bicicleta.

# Level / Nivel

Intermedio
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

45 min
(30 min to one hour)
(30 minutos a una hora)

**Comment by alexfernandez** [comment]
Buenas, suena muy interesante. ¿Qué disponibilidad tienes? Es posible que quede un hueco ahora a finales de septiembre, y si no la pasaríamos a octubre.

**Comment by furstenheim** [comment]
hasta final de octubre se me ha liado la cosa. Pero a partir de la mitad de noviembre cuando os venga bien

**Comment by alexfernandez** [comment]
Buenas de nuevo, ¿qué tal lo tienes para finales de mes? Por ejemplo el martes 28 de noviembre.

**Comment by furstenheim** [comment]
Me viene perfecto

**Comment by furstenheim** [comment]
@alexfernandez El 28 entonces?

**Comment by alexfernandez** [comment]
Vale, ¡buscamos sala! Mi mail es alexfernandeznpm@gmail.com, please envíame tu contacto y te pongo en copia.

**Comment by alexfernandez** [comment]
@furstenheim Vale, ¡buscamos sala! Mi mail es alexfernandeznpm@gmail.com, please envíame tu contacto y te pongo en copia.

**Comment by alexfernandez** [comment]
Hecho en https://www.meetup.com/es-ES/Node-js-Madrid/events/245463067/.
