### ISSUE TITLE
Clean Architecture en NodeJS

### ISSUE THREAD

**Issue by siro47** [NodeJsMadrid/talks#26]
# Title / Título
Clean Architecture en NodeJS

# Description / Descripción
El objetivo de la charla es presentar el modelo de arquitectura NodeJS al que hemos llegado en Solid GEAR tras un tiempo trabajando con esta tecnología. 
Contar problemas reales que nos hemos ido encontrando y como nos hemos basado en conceptos como 'Clean Architecture' o 'Arquitectura Hexagonal' para solventar esos problemas y llegar a una solución que, aunque siempre mejorable, ya sea mínimamente digna de ser calificada como escalable, desacoplada y sobre la que poder hacer tests automáticos de manera sencilla.

# Speaker Bio / Bio del Ponente
Siro Ramírez Losada, desarrollador FullStack en SolidGEAR y friki a tiempo parcial. Le encanta hacer magia con el software. Apasionado de las metodologías ágiles y el desarrollo de videojuegos. @sirillo47

# Level / Nivel
Intermedio

# Duration / Duración
45 min

**Comment by alexfernandez** [comment]
Buenas, se nos ha quedado un hueco. ¿Te viene bien hacerla el próximo 26 de septiembre, martes?

**Comment by siro47** [comment]
Vale, sí, sin problema.

**Comment by alexfernandez** [comment]
¡[Anunciado](https://www.meetup.com/es-ES/Node-js-Madrid/events/243484449/)! Nos vemos en Kunlabori la semana que viene :)
