### ISSUE TITLE
Running NodeJS web-apps on Kubernetes clusters

### ISSUE THREAD

**Issue by jcleira** [NodeJsMadrid/talks#28]
# Title / Título

Running NodeJS web-apps on Kubernetes clusters

# Description / Descripción

Disclaimer: This description it's about a workshop proposal non a talk one. The idea of this proposal is to create a hands-on workshop for ~20 people.

The workshop focus would be to go from zero to a production ready Kubernetes cluster running a nodeJS web-app. So every assistant will live launch a Kubernetes cluster on a AWS account that will be provided. In order to make the cluster production ready we will also deploy monitoring tooling using [Prometheus](https://prometheus.io/) and [Grafana](https://grafana.com/) and a logs ingester using [oklog](https://github.com/oklog/oklog).

El focus del workshop será ir desde cero hasta tener un cluster de kubernetes que sea "production ready" con una aplicación web de NodeJS deployada en él. Cada asistente lanzará en vivo un cluster de Kubernetes en una cuenta de AWS a la que se tendrá acceso durante el workshop. Para conseguir que el cluster sea production ready desplegaremos [Prometheus](https://prometheus.io/) y [Grafana](https://grafana.com/) como herramientas de monitorización y [oklog](https://github.com/oklog/oklog) para el almacenamiento de logs.

# Speaker Bio / Bio del Ponente

Jose Corral - Devops & Full Stack developer por demasiados años para reconocerlo, ex-CTO de Kerad Games y actualmente contractor / freelance.

# Level / Nivel

(Intermediate, Advanced)
(Intermedio, Avanzado)

# Duration / Duración

(One hour and a half)
(Una hora y media)

**Comment by jcleira** [comment]
@alexfernandez ha pasado un poco de tiempo desde que te dije que la colgaría 😄  pero necesitaba confirmar fechas de mi visita a Madrid.

En realidad quizás te lo pongo un poco justo de tiempo porque sólo tendría una fecha que sería el **jueves día 2 de Noviembre**. ¿Como lo ves?

**Comment by alexfernandez** [comment]
Nos lo pones difícil, sí 😄  Veremos qué podemos hacer.

**Comment by alexfernandez** [comment]
¡Hecha! Gracias, @jcleira 😸
