### ISSUE TITLE
NodeJS Sólido con TypeScript, Jest y NestJS

### ISSUE THREAD

**Issue by RafaelCasuso** [NodeJsMadrid/talks#31]
# NodeJS Sólido con TypeScript, Jest y NestJS

# Descripción
Las aplicaciones NodeJS de alta modularización y baja estructura han permitido una explosión de esta tecnología, pero adolecen de la seguridad y solidez que otras tecnologías con más madurez alcanzan en producción. Por este motivo han surgido frameworks sobre Node como NestJS que permiten utilizar las mejores prácticas de desarrollo que nos permitan construir las aplicaciones más fiables y sólidas posibles.

Esta charla incluye cómo podemos hacer que un proyecto NodeJS brille con:

- Arquitectura física del proyecto predecible
- Componentización y desacoplamiento de las diferentes piezas
- Controladores, Componentes, Módulos, Middlewares, Pipes, Interceptors.
- Comprobación sólida de entrada y salida de datos
- Inyección de dependencias
- Manejo de errores
- Testing Unitario de todos los componentes
- Testing E2E

# Bio del Ponente
CTO en Stay y CEO de SnowStorm con más de 10 años de experiencia desarrollando tanto Frontend como Backend, especializado en tecnologías como BackboneJS, ReactJS, VueJS y Arquitectura NodeJS aplicada a Inteligencias Conversacionales y Aplicaciones de Comunicación en Tiempo Real. Organizador de las comunidades VueJS Madrid y Bot Development Madrid.

# Nivel
Intermedio

# Duración
45 minutos

**Comment by alexfernandez** [comment]
Buenas, @RafaelCasuso, ¿qué tal te viene a finales de abril?

**Comment by RafaelCasuso** [comment]
Aunque si pudiera ser la siguiente (la del 30) me vendría mejor

**Comment by alexfernandez** [comment]
Hum, ¿seguro? La del 30 es la semana del puente de mayo...

**Comment by RafaelCasuso** [comment]
Tienes razón, mejor semana del 23, si pudiera ser hacia el final (Jueves o Miércoles) mejor.

**Comment by alexfernandez** [comment]
¡Hecho! [Link](https://www.meetup.com/es-ES/Node-js-Madrid/events/249616574/).
