### ISSUE TITLE
Introducción a NestJS

### ISSUE THREAD

**Issue by raguilera82** [NodeJsMadrid/talks#32]
# Title / Título
Introducción a NestJS
# Description / Descripción
Cuando un desarrollador de Java se tiene que enfrentar al reto de programar en NodeJS, busca por todos los medios algo que le recuerde a su amado Spring. Pues bien NestJS es un framework que nos propociona inyección de dependencias con sintaxis de TypeScript muy parecida a Angular que facilita la construcción de API REST y Websockets, el trabajo con GraphQL, la comunicación entre microservicios y el testing general de la aplicación, entre otras cosas, con el fin de hacernos productivos desde el minuto 1.
En la charla se va a ver una introducción a este framework y mediante código en vivo se va a abordar la construcción de un API REST desde cero.
# Speaker Bio / Bio del Ponente
Rubén Aguilera es un profesional con más de 10 años de experiencia que, desde 2009, desempeña su trabajo en [Autentia](http://www.autentia.com) como consultor tecnológico, donde ha tenido la oportunidad de trabajar y formarse en muy distintas metodologías, herramientas y tecnologías tanto de servidor como de cliente. Comparte su conocimiento escribiendo tutoriales en la web [www.adictosaltrabajo.com] (http://www.adictosaltrabajo.com/)
# Level / Nivel
Iniciación
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
45 minutos
(30 min to one hour)
(30 minutos a una hora)

**Comment by raguilera82** [comment]
En vista de que existen programadas ya varias charlas sobre este tema muy cercanas en el tiempo.... 24 de Abril la de Rafael en este Meetup y la del 10 de Mayo en MadridJS... cancelo esta propuesta para no saturar el tema... Saludos

**Comment by alexfernandez** [comment]
De acuerdo, ¿alguna otra que quieras proponer? :smile:
