### ISSUE TITLE
10 patrones de diseño para Node

### ISSUE THREAD

**Issue by feliun** [NodeJsMadrid/talks#34]
# Title / Título
10 patrones de diseño para Node

# Description / Descripción
"Si el código funciona, eso es lo que cuenta" es una de las falacias más escuchadas en el mundo del desarrollo de software.

Los patrones de diseño presentados en esta charla para Javascript te ayudarán a crear un código más legible, mantenible y comunicativo.

# Speaker Bio / Bio del Ponente
Felipe Polo, ingeniero full stack en GuideSmiths. Amante de Node y las arquitecturas de microservicios.

# Level / Nivel
Intermedio

# Duration / Duración
50 minutos

**Comment by alexfernandez** [comment]
Buenas, @feliun, llegamos a tu propuesta, ¿qué tal te viene hacerla a finales de mayo?

**Comment by feliun** [comment]
Hola @alexfernandez. Tendría disponibilidad. ¿Entre el 28 y el 31 por ejemplo?

**Comment by alexfernandez** [comment]
¡Perfect! Vamos a apuntar al 31, voy pidiendo sala.

**Comment by alexfernandez** [comment]
Hecha, ¡gracias! https://www.meetup.com/es-ES/Node-js-Madrid/events/250575825/
