### ISSUE TITLE
¿Qué puede hace Rust por mi Node.js?

### ISSUE THREAD

**Issue by jrvidal** [NodeJsMadrid/talks#36]
# Title / Título

## ¿Qué puede hace Rust por mi Node.js?

# Description / Descripción

[Rust](http://rust-lang.org/) es un lenguaje moderno de programación de sistemas que "desbloquea" las capas de software de más bajo nivel para todos los desarrolladores. Es un lenguaje con una perspectiva y una manera de trabajar diametralmente opuesta. Y sin embargo, el combo Rust + Node.js permite una serie de posibilidades muy interesantes. En esta charla presentaremos un menú con diferentes escenarios (algunos más serios, otros más alocados):

* Quiero algo de Rust con mi Node.
* Quiero algo de [WebAssembly](http://webassembly.org/) con mi Node.
* Quiero algo de Rust en vez de mi Node.
* Quiero re-inventar Node.

# Speaker Bio / Bio del Ponente

Roberto Vidal, Software Engineer en Tuenti. Amante de Rust y desarrollador de Node.js desde los tiempos de la versión 0.6.

# Level / Nivel

Intermedio.

# Duration / Duración

30 - 50 minutos (\*)

(\*): Esta charla es un tanto atípica en cuanto a que habla de una tecnología relativamente "ajena". Dependiendo del interés quizá sería más apropiado darla como un [entremés](https://es.wikipedia.org/wiki/Entrem%C3%A9s) más breve (20-30 minutos). Por mi parte, yo puedo hablar de Rust sin parar :wink:

**Comment by alexfernandez** [comment]
Buenas, ¿estás disponible para finales de mes?

**Comment by jrvidal** [comment]
¡Buenas! ¿Para qué semana? Hay un meetup de https://github.com/MadRust cociéndose para la semana del 20 y en principio me gustaría atender.

**Comment by alexfernandez** [comment]
En principio hacemos los meetups el último jueves del mes, que sería el jueves 27 de septiembre, pero podemos adaptarnos a lo que prefieras.

**Comment by jrvidal** [comment]
:+1: Contad conmigo. No veo que tengáis más charlas propuestas, o sea que ¿imagino que sería plato fuerte, no entremés?

**Comment by alexfernandez** [comment]
¡Hecha, gracias!
