### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by devopsapiens** [NodeJsMadrid/talks#38]
# Title / Título

# Description / Descripción

# Speaker Bio / Bio del Ponente

# Level / Nivel

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

(30 min to one hour)
(30 minutos a una hora)

# Constraints / Condicionantes

(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)

**Comment by alexfernandez** [comment]
¡Hola! No veo nada de contenido, cierro el issue hasta que le des forma.
