### ISSUE TITLE
Charla: Desarrollando Skills Alexa con AWS Lambda y node.js

### ISSUE THREAD

**Issue by germanviscuso** [NodeJsMadrid/talks#39]
- Título de la charla: Desarrollando Skills Alexa con AWS Lambda y node.js
- Descripción: Alexa, el servicio basado en la voz dentro de Amazon Echo, incorpora un conjunto de habilidades, o Skills, que permiten a los usuarios interactuar con distintas tecnologías y servicios utilizando el lenguaje natural. Los desarrolladores pueden también crear Skills personalizadas que pueden ser publicadas en el Alexa App Store y utilizadas desde cualquier dispositivo que incorpore Alexa. Durante esta sesión hablaremos sobre porqué creemos que la voz es el futuro de la experiencia de usuario (UX), echaremos un vistazo a la estructura del Alexa Engine y finalmente demostraremos como construir una Skill Alexa personalizada con el Alexa SDK para node.js y AWS Lambda.
- Bio de ponente: German es fanático de los ordenadores desde muy temprana edad. Comenzo su carrera profesional como software developer y luego se orientó a roles de developer advocacy. Durante su carrera ha tenido oportunidad de participar en muchos proyectos de diferentes industrias en grandes empresas (como desarrollador, escritor técnico, tech evangelist, community manager y consultor, entre otros). Tiene pasión por la tecnología y por hacerla accesible e interesante a otras personas (lo que lo llevó a participar en proyectos relacionados con crear y hacer crecer comunidades de desarrolladores). Sus intereses principales incluyen tecnologías de voz (ASR/NLU y diseño de VUI/VUX) ya que cree que serán las principales impulsoras de innovación en las interacciones humano-máquina durante las siguientes décadas.

**Comment by alexfernandez** [comment]
¡Hecho! https://www.meetup.com/es-ES/Node-js-Madrid/events/255854930/
