### ISSUE TITLE
Introducción a Meteor

### ISSUE THREAD

**Issue by manufosela** [NodeJsMadrid/talks#4]
**[Meteor](www.meteor.com)** *es un entorno simple basado en NodeJS para la construcción de sitios web modernos en cuestión de horas.

**Principios de Meteor**

 * **Data on the Wire**. Meteor no envía HTML través de la red. El servidor envía los datos y se renderizan en el cliente.

* **One Language**. Meteor usa Javascript tanto en el cliente como en el servidor.

* **Database Everywhere**. Puede usar los mismos métodos para acceder a su base de datos desde el cliente o el servidor.

* **Latency Compensation**. En el cliente, Meteor precarga datos y simula modelos para usarlos como llamadas a métodos de una clase que devuelve los datos inmediatemente.

* **Full Stack Reactivity**. En Meteor, en tiempo real está por defecto. Todas las capas, desde la base de datos a la plantilla, se actualizan automáticamente ante cualquier cambio.

* **Embrace the Ecosystem**. Meteor es de código abierto y se integra con las herramientas y marcos de código abierto existentes.

* **Simplicity Equals Productivity**. La mejor manera de hacer que algo parezca sencillo es hacerlo sencillo. La principal funcionalidad de Meteor es ser claro y APIs sencillas.

**Comment by alexfernandez** [comment]
Ya tenemos hora y fecha: día 27 a las 19:00, en kunlabori; espero que no haya problema. Charla de una media hora. ¿Me pasas una bio corta para la convocatoria? ¡Gracias!

**Comment by manufosela** [comment]
A ver si esto te vale ;)

Disfruto creando, analizando y desarrollando aplicaciones web desde 1997.
Desde hace 6 años, Orange me paga por disfrutar de mi mayor hobby.
Aficionado a tocar al guitarra y a la cocina.
Blogger de pintxos.paratorp.es.

**Comment by alexfernandez** [comment]
¡Publicado! :)

**Comment by alexfernandez** [comment]
Charla dada con gran éxito de crítica y público, cierro.
