### ISSUE TITLE
Aprendiendo mixins con "Plants vs Zombies"

### ISSUE THREAD

**Issue by feliun** [NodeJsMadrid/talks#41]
# Title / Título
Aprendiendo mixins con "Plants vs Zombies".

# Description / Descripción
Los mixins son un recurso muy potente en JS. Los descubriremos creado código básico para el juego "Plants vs Zombies".

# Speaker Bio / Bio del Ponente
Felipe Polo, Managing Director en GuideSmiths. Apasionado de Node y las arquitecturas de microservicios.

# Level / Nivel
Intermediate

# Duration / Duración
50 minutos

# Constraints / Condicionantes
Depende de la fecha!

**Comment by alexfernandez** [comment]
¡Buenas! ¿En qué fechas puedes?

**Comment by feliun** [comment]
Hola @alexfernandez ! Pues mira, por dar algunas fechas tentativas: 6, 9 o 13 de mayo?

Gracias.

**Comment by alexfernandez** [comment]
El 9 de mayo sería genial. Si confirmas vamos buscando sala.

**Comment by feliun** [comment]
Confirmado!

**Comment by alexfernandez** [comment]
[Hecha](https://www.meetup.com/es-ES/Node-js-Madrid/events/261023012/).
