### ISSUE TITLE
Multiplica por 10 tu rendimiento usando Streams

### ISSUE THREAD

**Issue by Betisman** [NodeJsMadrid/talks#42]
# Title / Título
Multiplica por 10 tu rendimiento usando Streams

# Description / Descripción
La charla será una introducción a los streams de Node.js.
El objetivo es introducir el concepto de streams y que podamos inferir en qué soluciones incluirlas y obtener una ganancia importante en el rendimiento de nuestras aplicaciones.
Se responderá a preguntas como ¿Qué son? ¿Para qué se usan? ¿Cómo? ¿Por qué debemos utilizarlas?
Hablaremos de event emitters, pipes, tipos de streams, backpressure y se mostraran varios ejemplos sobre cómo se pueden implementar, junto a casos de uso con los que comprobar las mejoras de rendimiento que se obtiene al utilizarlas.

# Speaker Bio / Bio del Ponente
Carlos Jiménez, ingeniero full stack y team lead en Guidesmiths.

# Level / Nivel
Intermedio

# Duration / Duración
45 minutos

# Constraints / Condicionantes
La fecha, que no puedo cualquier día.

**Comment by alexfernandez** [comment]
¡Suena interesante! ¿En qué fechas puedes?

**Comment by Betisman** [comment]
Buenas @alexfernandez , ¿puede ser en junio?

**Comment by alexfernandez** [comment]
Claro, el día que nos digas.

**Comment by alexfernandez** [comment]
¿Te viene bien a finales de junio? ¿Tienes sitio o lo buscamos? Y finalmente, ¿te importaría compartir fecha con otra charla?

**Comment by Betisman** [comment]
Buenas, @alexfernandez , disculpa.

Sí, me va bien a finales de junio.
Lo del sitio, si lo tenéis fácil vosotros, casi mejor, pero preguntaré "en casa" a ver si podemos reservar algo.

Si es necesario compartir fechas, no tengo inconveniente. Como mejor os venga a vosotros.

Gracias y disculpa, estaré más atento al correo.

**Comment by alexfernandez** [comment]
@Betisman Buscamos sitio nosotros, no hay problema. ¿Te viene bien el jueves 27 de junio?

**Comment by Betisman** [comment]
@alexfernandez me acabo de dar cuenta de que no confirmé. Sigue en pie? Por mí no hay problema. Mil disculpas.

**Comment by alexfernandez** [comment]
Habíamos cancelado el evento... Pero nos ha surgido otra propuesta que entrará en los próximos días. ¡Voy buscando sala!

**Comment by Betisman** [comment]
Genial. Ya me comentas. Gracias!

**Comment by alexfernandez** [comment]
¿Me puedes escribir a alexfernandeznpm@gmail.com para copiarte en los correos de la sala? ¡Gracias!

**Comment by Betisman** [comment]
Muchas gracias por todo @alexfernandez

**Comment by manufosela** [comment]
Hola! Esta charla la diste ya? Si no la diste, tienes disponibilidad par darle a finales de este mes

**Comment by alexfernandez** [comment]
Ya la hicimos, sí :)

**Comment by alexfernandez** [comment]
Ya la hicimos, sí :)

**Comment by Betisman** [comment]
Gracias!
