### ISSUE TITLE
Taller de uso de perf_hook

### ISSUE THREAD

**Issue by pabloalmunia** [NodeJsMadrid/talks#43]
# Title / Título

Taller de uso de perf_hook

# Description / Descripción

Taller práctico donde se aprenderá a utilizar las opciones más interesantes del paquete estándar perf_hook para la medición del rendimiento de nuestro código.

# Speaker Bio / Bio del Ponente

Persona extraña, bastante polifacética, pero sobre todo, enamorado de la programación desde hace varias décadas.

# Level / Nivel

Intermedio 

# Duration / Duración

1:30

# Constraints / Condicionantes

Me adapto.

**Comment by alexfernandez** [comment]
¡Buenas! ¿Te viene bien hacer este taller a finales de mayo? ¿Tienes sitio, o lo buscamos? ¿Entre semana o en finde?

**Comment by pabloalmunia** [comment]
Hola Alex,

1)	Fechas. En mayor puedo hasta el 29, el 30 salgo par a Berlín (voy a la JSConfEU)

2)	Sitio. No tengo sitio. Mi oficina está bastante alejada del centro.

3)	Diario o fin de semana: mejor un día de 19:00 a 20:30 o de 19:30 a 21:00, no es un taller muy largo y creo que es mejor de diario.

Un saludo
Pablo

**Comment by alexfernandez** [comment]
¿Te parece que lo organicemos a finales de mes? Por lo que dices el 28 podría ser buena fecha.

**Comment by pabloalmunia** [comment]
Me viene perfecto el 28 de mayo. 

P

**Comment by alexfernandez** [comment]
Perfecto, vamos buscando sala entonces.

**Comment by alexfernandez** [comment]
Acabo de darme cuenta de que el 28 de mayo tenemos un taller de MadridJS, ¿lo podemos dejar para el miércoles 29?

**Comment by pabloalmunia** [comment]
Me es bastante más complicado, pero no imposible. Adelanto una reunión que tengo antes.

 

Entonces lo dejamos para el día 28 a las 19:00

 

 

De: Alex Fernández <notifications@github.com> 
Enviado el: jueves, 16 de mayo de 2019 0:51
Para: NodeJsMadrid/talks <talks@noreply.github.com>
CC: pabloalmunia <pabloalmunia@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [NodeJsMadrid/talks] Taller de uso de perf_hook (#43)

 

Acabo de darme cuenta de que el 28 de mayo tenemos un taller de MadridJS, ¿lo podemos dejar para el miércoles 29?

**Comment by alexfernandez** [comment]
Hum, el *miércoles 29* sería ^_^

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/Node-js-Madrid/events/261674721/).
