### ISSUE TITLE
nodejs + cognitive smart agents + collaborative IAs

### ISSUE THREAD

**Issue by iav2014** [NodeJsMadrid/talks#44]
# Title / Título
Collaborative Artificial Intelligence: computer vision & smart agents &  cognitive services 
# Description / Descripción
Colaboracion entre diferentes disciplinas IA (smart agents, computer vision services),cognitive services in nodejs
# Speaker Bio / Bio del Ponente
Programmer by vocation. I have been lucky enough to be able to make my hobby a profession. Passionate about artificial intelligence and algorithms in general.
# Level / Nivel
intermedio
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
hora y media ya que hay online demo

(30 min to one hour)
(30 minutos a una hora)

# Constraints / Condicionantes
junio
(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)

**Comment by alexfernandez** [comment]
¡Buenas, Nacho! ¿Finales de junio te viene bien? ¿Tienes sitio, o buscamos uno?

**Comment by alexfernandez** [comment]
Y por último, ¿te importaría compartir fecha con otra charla?

**Comment by iav2014** [comment]
Hola,
En esta semana te digo, excepto el 28 de junio que cojo vacaciones. Tengo dos conferencias en junio pero aun no tengo fechas, son de everis y me lo diran en breve,
La semana del 24 excepto el 28 podria creo.
Compartir con otra charla que es?
Primero una y luego otra? A mi en principio me da igual ya me dices,
En vuanto tenga fechas de minponencia en nttdata te aviso para que no voincidan,,,


Enviado desde mi iPhone

**Comment by alexfernandez** [comment]
Sí, es hacer dos charlas seguidas. ¡Espero a que nos digas! :)

**Comment by alexfernandez** [comment]
@iav2014 ¿Te viene bien el jueves 27 de junio?

**Comment by manufosela** [comment]
Hola!
Esta charla sigue en pie?
Te interesa darla ahora en Enero o en Febrero!
Comentame cuando puedas para planificarla o cerrarla.

**Comment by iav2014** [comment]
Hola buenos dias,
se propuso hace ya tiempo efectivamente, y el diciembre pasado la imparti
en la universidad.
Si es de interés para el grupo de nodejs se podria organizar otra, pero ya
en febrero-marzo.
Everis estaba interesado en hacerla en sus instalaciones de su edificio de
castellana 77.
Si quieres puedo indagar y/o ponerte en contacto con el responsable de alli
para organizar el meetup.
Espero tu respuesta,
un saludo!

**Comment by manufosela** [comment]
Hola,

Pues por mi parte perfecto darla en febrero y si es en las instalaciones de
Everis ya tenemos el sitio :)
Si tuviera que ser en marzo comentame para buscar otra en febrero.

Gracias!

**Comment by iav2014** [comment]
buenos dias Manu,
pongo en copia a Felipe Polo, ya que estuve la semana pasada con él y
estaba interesado en organizar el meetup en sus instalaciones (desconozco
el aforo).
Si no pudiera ser ahi, ya te pondria en contacto con la gente que lleva
esto en everis.
A mi me vendria mejor gestionarlo para marzo (por si quieres dar paso a
otro meetup),
Os dejo presentado y hablais entre vosotros, y me vais contando

un saludo

**Comment by manufosela** [comment]
Perfecto. Cerramos para Marzo y hablo con Felipe para organizarlo en sus
oficinas.

Gracias!

Felipe cuando quieras lo vemos :)

**Comment by iav2014** [comment]
Buenas tardes,

Manu, coméntame si necesitáis ayuda con esto y lo movemos internamente.

Muchas gracias,

Un saludo

	

Felipe Polo Ruiz
Founder & Managing Director
GuideSmiths	

Mobile: +34 622 117 931
Website:  www.guidesmiths.com <https://www.guidesmiths.com/>
Address: Paseo de la Castellana, 43
                 28046 (Madrid), Spain

This message is for the named person(s) use only and it may contain confidential, proprietary or legally privileged information/documentation of GuideSmiths Spain S.L.. No confidentiality or privilege is waived or lost by any mistransmission. If the reader of this message is not the intended recipient then any distribution or copying of this communication is strictly prohibited. In this case please notify us immediately by telephone and mail the original message to us at the address gdpr@guidesmiths.com <mailto:gdpr@guidesmiths.com>..
In compliance with the provisions of the Regulation (EU) 2016/679 of the European Parliament and of the Council and the Organic Law 3/2018, on Protection of Personal Data and Guarantee of Digital Rights, we hereby inform you that the personal data will be treated with the due confidentiality and security measures required in accordance with our Privacy Policy <https://www.guidesmiths.com/privacy-policy>.

Este mensaje va dirigido a la persona(s) indicada(s) y puede contener información/documentación confidencial de carácter legal o personal de GuideSmiths Spain S.L. . La transmisión errónea del presente mensaje en ningún momento supone renuncia a su confidencialidad. Si el lector del mensaje no es el destinatario indicado cualquier copia o distribución de esta comunicación queda estrictamente prohibida. En este caso, rogamos que nos lo notifiquen inmediatamente por teléfono y que remitan el mensaje original a la dirección de correo electrónico  gdpr@guidesmiths.com <mailto:gdpr@guidesmiths.com>.
En cumplimiento de lo dispuesto en el Reglamento 2016/679, del Parlamento Europeo y del Consejo y la Ley Orgánica 3/2018, de Protección de Datos Personales y garantía de los derechos digitales, le informamos que los datos personales serán tratados con la debida confidencialidad y las medidas de seguridad exigidas de acuerdo con nuestra Política de Privacidad <https://www.guidesmiths.com/privacy-policy>.

**Comment by manufosela** [comment]
Hola!

Como queráis. Si lo moveis y lo dejamos cerrado por mi bien. Como es oara
Marzo hay márgen.
En cuanto tengamos fecha y sitio publico el evento.

Saludos,

Mánu

**Comment by alexfernandez** [comment]
¡Buenas! ¿Esta propuesta sigue en pie?

**Comment by alexfernandez** [comment]
Por favor reabre si la propuesta sigue en pie, ¡gracias!
