### ISSUE TITLE
Hermes Messenger, una aplicacion escalable, distribuida y tolerante a fallos, tan simple que es un juego de niños

### ISSUE THREAD

**Issue by ThePerkinrex** [NodeJsMadrid/talks#45]
# Title / Título
Hermes Messenger, una aplicación escalable, distribuida y tolerante a fallos, tan simple que es un juego de niños

# Description / Descripción
Alguna vez has pensado "esto es tan fácil que lo puede hacer un niño". Pues normalmente no es así, pero esta vez sí, y nosotros somos esos niños. 
Hermes Messenger es una aplicación de mensajería, que visualmente es como cualquier otra (en realidad más molona, no nos vamos a engañar), pero por dentro es mucho más. Posee un backend desarrollado en NodeJS, que está diseñado para tener alta disponibilidad, usando Cassandra para distribuir los datos y dar un servicio tolerante a fallos. Que podríamos habernos ganado la vida jugando al Fortnite, pero es que nos gustan los auténticos desafíos.

# Speaker Bio / Bio del Ponente
Somos 5 adolescentes que hemos estado trabajando en Hermes Messenger este curso en el Coderdojo de Majadahonda. Pondríamos más de nosotros, pero venimos a hablar de nuestro proyecto :)

# Level / Nivel
Intermedio (tiene conceptos avanzados, pero vamos a explicarlo a alto nivel, accesible a todos)

# Duration / Duración

45 minutos + preguntas

# Constraints / Condicionantes
Tendría que ser por la tarde.
***
[GitHub de Hermes Messenger](https://github.com/HermesMessenger)
[Hermes Messenger](https://hermesmessenger.chat)

**Comment by manufosela** [comment]
Hola!
¿Tienes disponibilidad para dar la charla ahora en Enero o en Febrero?

**Comment by alexfernandez** [comment]
¡Buenas! ¿Esta propuesta sigue en pie?

**Comment by alexfernandez** [comment]
Por favor reabre si la propuesta sigue en pie, ¡gracias!
