### ISSUE TITLE
Como desarrollar un Frontend en una arquitectura de Microservicios

### ISSUE THREAD

**Issue by kevinccbsg** [NodeJsMadrid/talks#48]
# Title / Título

Como desarrollar un Frontend en una arquitectura de Microservicios

# Description / Descripción

Trabajar en una arquitectura de microservicios es un reto que podemos encontrar en muchas de nuestras empresas. Aunque cada microservicio en sí es independiente y podemos trabajar con el de manera aislada, a veces, nos encontramos con que el desarrollo del Frontend no siempre está tan aislado, por lo que tenemos que crear entornos de desarrollo complejos para trabajar de manera local. Esto en muchos casos puede suponer un proceso complicado para los desarrolladores frontend o para el onBoarding de nuevos compañeros.

En esta charla, os compartiré mi experiencia de como desarrollamos una de nuestras aplicaciones en una arquitectura de microservicios, resolviendo estos problemas y consiguiendo que la parte frontend pueda centrarse en lo que mejor sabe hacer, crear experiencias de usuario increíbles.

# Speaker Bio / Bio del Ponente

Javascript Developer en Guidesmiths, apasionado de las tecnologías Web y la formación constante. Actualmente me dedico con tecnologías como Node.js, React, Docker, MongoDB y Cypress creando Microservicios y aplicaciones para empresas de Holanda y Suecia. También imparto formación de Javascript para distintas empresas.

# Level / Nivel

Intermedio

# Duration / Duración

45 minutos

# Constraints / Condicionantes

Algunas semanas lunes, martes y jueves no puedo pero dependería de la fecha. Por todo lo demás sin problemas.

**Comment by alexfernandez** [comment]
¡Gracias! ¿Esta propuesta sigue en pie?

**Comment by kevinccbsg** [comment]
Hola @alexfernandez que bueno que volvió el meetup 👏 pues ya di varias veces esta charla en el 2020.

Ahora estaba trabajando en una charla sobre AI con NodeJS (ese no es el título jaja). Es una charla, donde cuento mi experiencia a la hora de crear con Node.js una app como la del video que te dejo más abajo. Que utiliza OpenAI, base de datos de vectores para búsquedas (weaviate), Langchain para crear un chatbot y como hacer el stream a un formulario de react de la respuesta del AI.

Normalmente este tipo de herramientas viene bastante info en python pero no tanta para Node.js. Además en la charla quiero mostrar un poco, el coste que hemos tenido de desarrollo y otros problemas.

https://clipchamp.com/watch/3RuQPW7oAwt

Si os cuadra puedo pasarte la descripción y título y además sería con otro ponente @SabrinaFZ

**Comment by alexfernandez** [comment]
¡Claro que me cuadra! Si quieres cierra ésta y envía la nueva propuesta, igual la podemos hacer en septiembre si te viene bien.

**Comment by alexfernandez** [comment]
¿Te viene bien septiembre entonces? Please envía la propuesta para ir buscando sitio.
