### ISSUE TITLE
Introducción a NodeJS

### ISSUE THREAD

**Issue by MaiteHR** [NodeJsMadrid/talks#5]
Single Page Application con NodeJS, AngularJS and MongoDB.

**Comment by alexfernandez** [comment]
¡Llegó el momento! :)  ¿Te viene bien el martes 24 de febrero?

**Comment by alexfernandez** [comment]
¡De nuevo llegó el momento! ¿Te viene bien el lunes 23 a las 19:00? Ya tenemos la sala. Ah, y necesito una breve descripción y tu bio. Si quieres pásame por mensaje de Meetup tu dirección de correo para ponerte en copia. ¡Gracias!

**Comment by alexfernandez** [comment]
Cierro esta charla, reabre si vuelves a estar interesada :)
