### ISSUE TITLE
Estos tests no pueden tardar tanto, así no se puede trabajar.

### ISSUE THREAD

**Issue by jfbarea** [NodeJsMadrid/talks#50]
# Título
Estos tests no pueden tardar tanto, así no se puede trabajar.

# Descripción
Nuestra suite de tests end to end tardaba 40 minutos en ejecutarse, lo cual dificultaba muchísimo el despliegue continuo 😅 . En esta charla os quiero contar cómo redujimos esos 40 minutos a 5. La solución fue simple: hacer las cosas bien. Si casualmente tienes una batería de test mal hecha y quieres saber cómo mejorarla o si, simplemente, quieres venir a insultarme y decirme lo ignorante que era por haber hecho las cosas tan mal en un principio, esta es tu charla.

# Bio del Ponente
Soy Fran Barea. Soy un friki como tú. Me gusta hablar en público y contar mis cosas, además trabajo en mediasmart como frontend lead.
# Nivel
Principiante / Intermedio

# Duration / Duración
45 minutos

# Condicionantes
Puedo dar la charla cualquier día entre semana por la tarde excepto los martes.

**Comment by alexfernandez** [comment]
Publicado para el jueves 2023-06-22: https://www.meetup.com/es/node-js-madrid/events/294136602/

**Comment by alexfernandez** [comment]
Lista: https://www.meetup.com/es/node-js-madrid/events/294136602/
