### ISSUE TITLE
Not MEAN ORMs

### ISSUE THREAD

**Issue by gootyfer** [NodeJsMadrid/talks#6]
### Descripción
Cuando tratamos de arrancar un proyecto rápido con NodeJS la mayoría de las alternativas están opinionadas al stack MEAN. Pero algunos somos más celosos de nuestros datos, así que preferimos usar bases de datos sí(S)QL. Una solución es utilizar Sequelize un ORM (Object-Relational-Mapper) para NodeJS con soporte para bases de datos SQL, como postgres o SQLite.

En esta charla quería contaros los primeros pasos con Sequelize para arrancar un proyecto rápido en NodeJS + express + postgres. Además es tan molón que usa siempre promesas. El nivel de la charla será básico-intermedio.

### Sobre mí
Soy tipo corriente, con ganas de averiguar cómo funcionan las cosas. Apasionado de la innovación educativa. Ahora dedico todo mi tiempo a @h4ckademy

**Comment by alexfernandez** [comment]
¡Interesante! En principio te tocará alrededor de marzo, te avisaremos con tiempo. ¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, ha quedado un hueco para este mes, el martes 24 de febrero, ¿te animas?

**Comment by gootyfer** [comment]
Yo creo que sí. Supongo que habrá más charlas esa sesión, no? Y también me interesa saber dónde será para saberlo.

**Comment by alexfernandez** [comment]
Sí, en el [README](https://github.com/NodeJsMadrid/talks) puedes ver una charla de @MaiteHR que estoy intentando confirmar con ella. El sitio también está pendiente de confirmar, he pedido sala en Kunlabori.

**Comment by gootyfer** [comment]
Genial! Pero no digas que es avanzada, que no lo es :P

**Comment by alexfernandez** [comment]
Oye, si no es avanzada, la dejamos para marzo como introductoria, que tenemos más escasez.

**Comment by gootyfer** [comment]
Como decía en la descripción, yo diría que es de nivel "básico-intermedio". Pero creo que tira más a básico. Así que casi mejor en marzo si hay escasez.

**Comment by alexfernandez** [comment]
Perfecto. A ver si me responde @MaiteHR, o si no, guardamos la tuya en la recámara :)

**Comment by alexfernandez** [comment]
Me ha pedido @MaiteHR que dejemos la suya para marzo, ¿te importa salir al ruedo el martes 24 de febrero? Y perdona el mareo :)

**Comment by gootyfer** [comment]
Adelante!! :) Me lo apunto
