### ISSUE TITLE
Fork node.js, let's io.js

### ISSUE THREAD

**Issue by Serabe** [NodeJsMadrid/talks#7]
# Descripción

io.js es una implementación compatible con el ecosistema node y npm. ¿Pero qué nos ha llevado hasta este punto? ¿Qué dramas nos han llevado hasta esta escisión? ¿Esto mejora o empeora el panorama?

En esta charla analizaremos los hechos tanto técnicos como _políticos/de marketing_ que han provocado esta escisión y cuáles son su consecuencias en ambos niveles.

# Bio

Rubysta y embereño de corazón, se ve forzado a trabajar con JavaScript y node para poder hacer aplicaciones ember de la mejor manera posible. Aunque lo niegue en público, trabajar con JavaScript todo el día no le disgusta y hasta los disfruta.

¡Ah, sí! Lo de siempre: Developer. Mathematician. Troll.

**Comment by alexfernandez** [comment]
Tiene pinta de ser una charla avanzada... En principio el próximo hueco es en marzo, te avisaremos con tiempo para fijar la fecha.

**Comment by alexfernandez** [comment]
Quería decir en abril, más bien.

**Comment by alexfernandez** [comment]
Por misterios de la planificación se ha abierto un hueco para febrero, la charla será seguramente el martes 24 de febrero. ¿Te animas? Creo que es un tema de rabiosa actualidad, y cuanto antes mejor.

**Comment by Serabe** [comment]
Ok.

-- 
Sergio Arbeo
https://twitter.com/Serabe
