### ISSUE TITLE
Desarrollo Web en Node.js con Pillars.js

### ISSUE THREAD

**Issue by lilxelo** [NodeJsMadrid/talks#8]
# Descripción
Buenas!, la charla está orientada a conocer cómo funciona [Pillars.js,  un framework de desarrollo web modular y escalable en NodeJS](http://www.pillarsjs.com).

Pillars.js no está basado en ningún otro framework ni usamos librerías como connect, es un planteamiento de base diferente para conseguir la máxima escalabilidad y modularidad.

Llevamos casi un año trabajando en el, el código está iterado y refactorizado a reventar, al igual que el planteamiento y soluciones aportadas :-). Lo liberamos con licencia MIT, así que estamos bastante entusiasmados con que sea de utilidad para toda la comunidad de desarrolladores. 

### Contenidos
+ Repaso rápido a Node.js
+ Pillars.js
  + ¿Qué es Pillars.js?
  + Alcance y ventajas
+ Galería de ejemplos funcionales
+ Visión General de Pillars.js
+ Elementos del framework
+ Turno de preguntas

Si os interesa, la charla la podríamos hacer para Abril-Mayo y coincidiría con la presentación del framework en sociedad :P y por lo tanto con la primera versión estable :) 

# Sobre mí
Desarrolladora web :-) actualmente trabajando mucho en la documentación, referencia y tutoriales de Pillars.js. Realizando también pruebas unitarias. 

Por otra parte, ya sufrí los efectos físicos del desarrollo, así que intento ir a diario al gimnasio y comer sano xD.

**Comment by alexfernandez** [comment]
Cool! ¿Lo ves más para un público no iniciado, o más bien avanzado? Yo creo que se podría orientar en cualquier sentido (y están ambos slots libres por ahora), pero igual encaja más como charla avanzada. Si no me dices lo contrario, en principio sería para abril como charla avanzada.

**Comment by lilxelo** [comment]
Hola!! Pues me parece genial, lo dejamos cerrado en charla avanzada para Abril :-) ¿Sobre qué día podría ser?

**Comment by alexfernandez** [comment]
Normalmente lo hacemos el último martes del mes, salvo que haya algún motivo en contra. Eso nos da el... 28 de abril. Pero no te lo apuntes todavía en la agenda: te avisaremos con unas cuantas semanas de antelación.

**Comment by lilxelo** [comment]
Buenas Alex, he tenido un accidente de tráfico y estoy de baja :_(. No es grave, aunque estoy con la espalda hecha un cristo. Me temo que vamos a tener que posponer la charla a cuando termine la rehabilitación. Con las ganas que tenía de subir a Madrid :(. Bueno, te aviso cuando esté bien para retomar la charla, ok?

**Comment by alexfernandez** [comment]
Faltaría más, no hay problema. ¡Que te mejores!
