### ISSUE TITLE
Punky Programming with NodeJS  (NodeJS para construir T-cracia)

### ISSUE THREAD

**Issue by aluarosi** [NodeJsMadrid/talks#9]
# Título (tentativo)
Punky Programming with NodeJS | Getting Real with NodeJS | ...

# Descripción de la charla
T-cracia es una aplicación que mide la actividad política española en Twitter. Después de 6 meses monitoriza 700 cuentas de partidos y políticos españoles.  http://t-cracia.info
Me gustaría compartir mi experiencia, muy particular, del uso de NodeJS en un proyecto de mínimos recursos donde predomina la idea antes que la implementación. Espero que sirva para animar al uso de NodeJS en proyectos experimentales, a explorar rompiendo las reglas y a aprender NodeJS haciendo. 

* El papel NodeJS como corazón de una arquitectura "políglota" que incluye Django, MongoDB, Postgresql, Redis, AngularJS, D3JS, ...
* Nuestro estilo de NodeJS: no-promises, no-ORM, no-objects, no-loops, not-object-oriented, no-frills.
* Cómo tratar de no pagar (todavía) en Heroku.
* Mucha participación de los asistentes contrastando su propia experiencia.

# Bio
Ingeniero de Teleco, he transitado el camino de las redes, los sistemas y finalmente el software. Descubrí que el código es mi herramienta para plasmar y comunicar ideas. Programo en Python y Javascript. Ahora: enganchado a Clojure. http://dofideas.com

**Comment by alexfernandez** [comment]
¡Cool, necesitamos charlas de iniciación! Te apunto en principio para abril, si te viene mal lo retrasamos. Nos pondremos en contacto contigo unas semanas antes de la charla.

**Comment by aluarosi** [comment]
Perfecto!

**Comment by therealpablors** [comment]
Muy interesante esta charla. Me apunto ya!

**Comment by alexfernandez** [comment]
Atraco a mano armada: ¿cómo te viene dar esta charla el próximo lunes día 23? Se nos ha caído la charla prevista...

**Comment by therealpablors** [comment]
Alex me encantaría. El caso es que salgo ya para el startup weekend de tenerife y regreso el lunes 23. Voy llegando como a las 18.30 al aeropuerto por lo que me da que no llegaría en condiciones para poder darla :( Y créeme que me apetece mucho.

**Comment by alexfernandez** [comment]
Pablo, tú no eres quien ha propuesto esta charla sino Alvaro, no?

**Comment by therealpablors** [comment]
Efectivamente. Otra vez lo mismo, jaja. Github tiene ganas de que dé una charla. Seguramente estos mensajes se estén enviando a todos los que estemos enganchados a talks.

**Comment by alexfernandez** [comment]
A todos los que estén suscritos al issue, por ejemplo por haber comentado. Está claro que tienes que proponer una charla propia :)

**Comment by aluarosi** [comment]
Hola Alex,
disculpa no haberte contestado antes, estoy de viaje y sólo ahora pude mirar el correo.
Dime primero cuánto tiempo esperabas que dure mi charla.

**Comment by alexfernandez** [comment]
Media hora o así.
